package services

import (
	"bytes"
	"fmt"
	"travelmate/internal/domain"

	"github.com/jung-kurt/gofpdf"
)

type PDFService struct{}

func NewPDFService() *PDFService {
	return &PDFService{}
}

func (s *PDFService) GenerateTripPDF(trip domain.Trip, plan domain.TripPlan) ([]byte, error) {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetFooterFunc(func() {
		pdf.SetY(-15)
		pdf.SetFont("Arial", "I", 8)
		pdf.CellFormat(0, 10, fmt.Sprintf("Page %d | Generated by Miru App", pdf.PageNo()), "", 0, "C", false, 0, "")
	})

	pdf.AddPage()

	// 1. HEADER
	pdf.SetFont("Arial", "B", 26)
	pdf.SetTextColor(13, 148, 136) // Teal color
	pdf.Cell(0, 10, fmt.Sprintf("Trip to %s", trip.Destination))
	pdf.Ln(12)

	pdf.SetTextColor(0, 0, 0)
	pdf.SetFont("Arial", "", 12)
	// Parse StartDate (string) to display format
	dateStr := trip.StartDate // Already a string in YYYY-MM-DD format
	pdf.Cell(0, 8, fmt.Sprintf("Dates: %s (%d Days) | Style: %s", dateStr, trip.TripDays, trip.Style))
	pdf.Ln(15)

	// 2. HIGHLIGHTS & SUMMARY (If available)
	if plan.Tagline != "" {
		pdf.SetFont("Arial", "I", 14)
		pdf.MultiCell(0, 8, fmt.Sprintf("\"%s\"", plan.Tagline), "", "C", false)
		pdf.Ln(10)
	}

	if plan.MorningBriefing != "" {
		pdf.SetFont("Arial", "", 11)
		pdf.MultiCell(0, 6, plan.MorningBriefing, "", "L", false)
		pdf.Ln(10)
	}

	// 3. ITINERARY
	pdf.SetFont("Arial", "B", 18)
	pdf.SetFillColor(240, 253, 250) // Light Teal
	pdf.CellFormat(0, 12, "  Your Daily Itinerary", "", 1, "L", true, 0, "")
	pdf.Ln(5)

	for _, day := range plan.Itinerary {
		// Avoid page break inside a day header if possible
		if pdf.GetY() > 250 {
			pdf.AddPage()
		}

		pdf.SetFont("Arial", "B", 14)
		pdf.Cell(0, 10, fmt.Sprintf("Day %d: %s", day.Day, day.Title))
		pdf.Ln(8)

		pdf.SetFont("Arial", "", 10)
		for _, act := range day.Activities {
			// Time Column
			pdf.SetFont("Courier", "B", 10)
			pdf.Cell(20, 6, act.Time)

			// Activity Title
			pdf.SetFont("Arial", "B", 10)
			pdf.Cell(80, 6, act.Activity)

			// Location/Note
			pdf.SetFont("Arial", "I", 9)
			pdf.Cell(0, 6, act.PlaceName)
			pdf.Ln(6)

			// Description Line (Indented)
			if act.Description != "" {
				pdf.SetFont("Arial", "", 9)
				pdf.SetX(30) // Indent
				pdf.MultiCell(0, 5, act.Description, "", "L", false)
			}
			pdf.Ln(2)
		}
		pdf.Ln(5)

		// Separator line
		pdf.SetDrawColor(200, 200, 200)
		pdf.Line(10, pdf.GetY(), 200, pdf.GetY())
		pdf.Ln(5)
	}

	// 4. BUDGET BREAKDOWN
	pdf.AddPage()
	pdf.SetFont("Arial", "B", 18)
	pdf.CellFormat(0, 12, "  Estimated Budget Breakdown", "", 1, "L", true, 0, "")
	pdf.Ln(10)

	pdf.SetFont("Arial", "", 12)

	// Helper for budget row
	drawBudgetRow := func(label string, amount int) {
		pdf.Cell(100, 8, label)
		pdf.Cell(0, 8, fmt.Sprintf("IDR %d", amount)) // Simple formatter
		pdf.Ln(8)
	}

	drawBudgetRow("Transport", int(plan.BudgetBreakdown.Transport))
	drawBudgetRow("Accommodation", int(plan.BudgetBreakdown.Accommodation))
	drawBudgetRow("Food & Dining", int(plan.BudgetBreakdown.Food))
	drawBudgetRow("Activities & Tickets", int(plan.BudgetBreakdown.Tickets))
	drawBudgetRow("Miscellaneous", int(plan.BudgetBreakdown.Misc))

	pdf.Ln(5)
	pdf.SetFont("Arial", "B", 12)
	total := plan.BudgetBreakdown.Transport + plan.BudgetBreakdown.Accommodation + plan.BudgetBreakdown.Food + plan.BudgetBreakdown.Tickets + plan.BudgetBreakdown.Misc
	drawBudgetRow("TOTAL ESTIMATED", int(total))

	// 5. PACKING LIST (Optional)
	if len(plan.PackingList) > 0 {
		pdf.Ln(15)
		pdf.SetFont("Arial", "B", 18)
		pdf.CellFormat(0, 12, "  Smart Packing List", "", 1, "L", true, 0, "")
		pdf.Ln(5)

		for _, cat := range plan.PackingList {
			pdf.SetFont("Arial", "B", 12)
			pdf.Cell(0, 8, cat.Category)
			pdf.Ln(8)

			pdf.SetFont("Arial", "", 10)
			for _, item := range cat.Items {
				pdf.Cell(5, 6, "-")
				pdf.Cell(0, 6, item)
				pdf.Ln(6)
			}
			pdf.Ln(4)
		}
	}

	var buf bytes.Buffer
	err := pdf.Output(&buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
